### ISSUE TITLE
Please provide sample

### ISSUE THREAD

**Issue by sosie-js** [DJATOM/VapourSynth-atomchtools#3]
Hello @DJATOM ,

It would like good you provide us examples
In particulary, I struggle to use your ApplyImageMask with a RGB image and YUV video
 just to overlay an image on the video without washing colors..

using this
![9_PING_LOGO-480p](https://github.com/user-attachments/assets/dbb72c38-bb15-449c-972d-0d527a69e842)

with
```python

import vapoursynth as vs
from vapoursynth import core
from bssource import BSSource,Trim, Audio, AudioDub,TextSub

input=r'https://github.com/falsefiresite/falsefire.com/raw/master/videos/en/ff_en_2_128k_48k.mp4'
BSSource(input)
clip_in=Trim(7190,7200)
placeholder = core.std.BlankClip(clip_in.video, length=len(clip_in.video),color=[0, 0, 0],width=720, height=480)

c=ApplyImageMask(source=clip_in.video,replacement=placeholder, image_mask="9_PING_LOGO-480p.png",luma_only=False,preview=True,binarize_threshold=17,scaled_binarize=True)

AudioDub(c,clip_in.audio)
```
I got 
![image](https://github.com/user-attachments/assets/38e48ee3-0cc3-4634-b959-dfb5421537e8)

Thanks a lot !

**Comment by DJATOM** [comment]
ApplyImageMask should be used to cover source from filtration, where mask is the black and white map (white pixel means using from source and black - from filtration). In general it's just a wrapper on MaskedMerge to make mask from image.

If you want to overlay image, there is a better tool available: https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/master/havsfunc/havsfunc.py#L441

**Comment by sosie-js** [comment]
Thanks a lot @DJATOM , I will try then Overlay function =)
